//export var Constants = {  };
export var Constants = { 
    //API_ENDPOINT : '/ws/',
    API_ENDPOINT : 'https://www.esferasoluciones.com/api/trikygol/',
    months: [
        'Enero',
        'Febrero',
        'Marzo',
        'Abril',
        'Mayo',
        'Junio',
        'Julio',
        'Agosto',
        'Septiembre',
        'Octubre',
        'Noviembre',
        'Diciembre'
    ],
    stickers: {
        symbols: { name: 'Simbolos', range: [0,7] },
        stadiums: { name: 'Estadios', range: [8,19] },
        russia: { name: 'Rusia', range: [20,39] },
        saudi: { name: 'Arabia Saudita', range: [40,59] },
        egypt: { name: 'Egipto', range: [60,79] },
        uruguay: { name: 'Urugay', range: [80,99] },
        portugal: { name: 'Portugal', range: [100,119] },
        spain: { name: 'España', range: [120,139] },
        morocco: { name: 'Marruecos', range: [140,159] },
        islamicRep: { name: 'Iran', range: [160,179] },
        france: { name: 'Francia', range: [180,199] },
        australia: { name: 'Australia', range: [200,219] },
        peru: { name: 'Peru', range: [220,239] },
        denmark: { name: 'Dinamarca', range: [240,259] },
        argentina: { name: 'Argentina', range: [260,279] },
        iceland: { name: 'Islandia', range: [280,299] },
        croatia: { name: 'Croacia', range: [300,319] },
        nigeria: { name: 'Nigeria', range: [320,339] },
        brazil: { name: 'Brasil', range: [340,359] },
        switzerland: { name: 'Suiza', range: [360,379] },
        costaRica: { name: 'Costa Rica', range: [380,399] },
        serbia: { name: 'Serbia', range: [400,419] },
        germany: { name: 'Alemania', range: [420,439] },
        mexico: { name: 'Mexico', range: [440,459] },
        sweden: { name: 'Suecia', range: [460,479] },
        korea: { name: 'Corea del Sur', range: [480,499] },
        belgium: { name: 'Bélgica', range: [500,519] },
        panama: { name: 'Panamá', range: [520,539] },
        tunisia: { name: 'Túnez', range: [540,559] },
        england: { name: 'Inglaterra', range: [560,579] },
        poland: { name: 'Polonia', range: [580,599] },
        senegal: { name: 'Senegal', range: [600,619] },
        colombia: { name: 'Colombia', range: [620,639] },
        japan: { name: 'Japón', range: [640,659] },
        legends: { name: 'Leyendas', range: [660,669] },
    }
};